-- ==============================================================================
-- Supabase PostgreSQL Schema & Seed Data
-- Smart Student Management System
-- ==============================================================================
-- You can run this file directly in the Supabase Dashboard -> SQL Editor.
-- ==============================================================================

-- 1. Helper function for automatically updating updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2. Drop existing tables if re-running
DROP TABLE IF EXISTS report_cards CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;
DROP TABLE IF EXISTS fees CASCADE;
DROP TABLE IF EXISTS marks CASCADE;
DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS enrollments CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS teachers CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 3. Departments
CREATE TABLE departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  description TEXT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER update_departments_updated_at
  BEFORE UPDATE ON departments
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 4. Users (Authentication & Roles)
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'Student' CHECK (role IN ('Admin', 'Teacher', 'Student')),
  student_id BIGINT NULL,
  teacher_id BIGINT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER update_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 5. Students
CREATE TABLE students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id VARCHAR(40) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  dob DATE NULL,
  gender VARCHAR(20) NULL CHECK (gender IN ('Male', 'Female', 'Other')),
  nationality VARCHAR(80) NULL,
  phone VARCHAR(30) NULL,
  email VARCHAR(160) NULL UNIQUE,
  address TEXT NULL,
  parent_details TEXT NULL,
  emergency_contact VARCHAR(120) NULL,
  previous_school VARCHAR(160) NULL,
  semester VARCHAR(40) NULL,
  department VARCHAR(120) NULL,
  status VARCHAR(20) DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive', 'Graduated', 'Suspended')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER update_students_updated_at
  BEFORE UPDATE ON students
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 6. Teachers
CREATE TABLE teachers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id VARCHAR(40) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  department VARCHAR(120) NULL,
  specialization VARCHAR(160) NULL,
  email VARCHAR(160) NULL UNIQUE,
  phone VARCHAR(30) NULL,
  office_location VARCHAR(120) NULL,
  joining_date DATE NULL,
  salary NUMERIC(12,2) DEFAULT 0,
  role VARCHAR(80) DEFAULT 'Teacher',
  assigned_subjects TEXT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER update_teachers_updated_at
  BEFORE UPDATE ON teachers
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 7. Courses
CREATE TABLE courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id VARCHAR(40) NOT NULL UNIQUE,
  course_name VARCHAR(160) NOT NULL,
  credits INT NOT NULL DEFAULT 0,
  description TEXT NULL,
  prerequisite VARCHAR(160) NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER update_courses_updated_at
  BEFORE UPDATE ON courses
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 8. Enrollments
CREATE TABLE enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  status VARCHAR(20) DEFAULT 'Registered' CHECK (status IN ('Registered', 'Dropped', 'Completed')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_enrollment UNIQUE (student_id, course_id)
);

CREATE TRIGGER update_enrollments_updated_at
  BEFORE UPDATE ON enrollments
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 9. Attendance
CREATE TABLE attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  course_id BIGINT NULL REFERENCES courses(id) ON DELETE SET NULL,
  teacher_id BIGINT NULL REFERENCES teachers(id) ON DELETE SET NULL,
  class_name VARCHAR(120) NULL,
  attendance_date DATE NOT NULL,
  status VARCHAR(20) NOT NULL CHECK (status IN ('Present', 'Absent', 'Late', 'Excused')),
  remarks VARCHAR(255) NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER update_attendance_updated_at
  BEFORE UPDATE ON attendance
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 10. Marks
CREATE TABLE marks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  internal_marks NUMERIC(5,2) DEFAULT 0,
  assignment NUMERIC(5,2) DEFAULT 0,
  quiz NUMERIC(5,2) DEFAULT 0,
  project NUMERIC(5,2) DEFAULT 0,
  final_exam NUMERIC(5,2) DEFAULT 0,
  total NUMERIC(6,2) DEFAULT 0,
  grade VARCHAR(5) NULL,
  gpa NUMERIC(3,2) DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER update_marks_updated_at
  BEFORE UPDATE ON marks
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 11. Fees
CREATE TABLE fees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  tuition_fee NUMERIC(12,2) DEFAULT 0,
  hostel_fee NUMERIC(12,2) DEFAULT 0,
  bus_fee NUMERIC(12,2) DEFAULT 0,
  scholarship NUMERIC(12,2) DEFAULT 0,
  paid_amount NUMERIC(12,2) DEFAULT 0,
  pending_amount NUMERIC(12,2) DEFAULT 0,
  payment_status VARCHAR(20) DEFAULT 'Pending' CHECK (payment_status IN ('Pending', 'Partial', 'Paid')),
  receipt_no VARCHAR(80) UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER update_fees_updated_at
  BEFORE UPDATE ON fees
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 12. Schedules
CREATE TABLE schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_name VARCHAR(120) NOT NULL,
  room VARCHAR(80) NOT NULL,
  day VARCHAR(20) NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  teacher_id BIGINT NULL REFERENCES teachers(id) ON DELETE SET NULL,
  teacher_name VARCHAR(120) NULL,
  course_id BIGINT NULL REFERENCES courses(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER update_schedules_updated_at
  BEFORE UPDATE ON schedules
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 13. Notifications
CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(160) NOT NULL,
  message TEXT NOT NULL,
  type VARCHAR(30) NOT NULL CHECK (type IN ('New Assignment', 'Exam Date', 'Fee Reminder', 'Holiday Notice')),
  target_role VARCHAR(20) DEFAULT 'All' CHECK (target_role IN ('All', 'Admin', 'Teacher', 'Student')),
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER update_notifications_updated_at
  BEFORE UPDATE ON notifications
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 14. Audit Logs
CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR(160) NOT NULL,
  ip_address VARCHAR(80) NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 15. Report Cards
CREATE TABLE report_cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  semester VARCHAR(40) NULL,
  gpa NUMERIC(3,2) DEFAULT 0,
  cgpa NUMERIC(3,2) DEFAULT 0,
  generated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- Row Level Security (RLS) Setup
-- ==============================================================================
ALTER TABLE departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE marks ENABLE ROW LEVEL SECURITY;
ALTER TABLE fees ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE report_cards ENABLE ROW LEVEL SECURITY;

-- Allow full access to backend service role and authenticated app connections
DO $$
DECLARE
  tbl text;
BEGIN
  FOR tbl IN
    SELECT tablename FROM pg_tables WHERE schemaname = 'public'
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS "Allow service role full access" ON %I', tbl);
    EXECUTE format('CREATE POLICY "Allow service role full access" ON %I FOR ALL USING (true) WITH CHECK (true)', tbl);
  END LOOP;
END;
$$;

-- ==============================================================================
-- Initial Seed Data
-- ==============================================================================
INSERT INTO departments (name, description) VALUES
('Computer Science', 'Software, data, and systems programs'),
('Business Administration', 'Management and finance programs');

INSERT INTO students
(student_id, name, dob, gender, nationality, phone, email, address, parent_details, emergency_contact, previous_school, semester, department, status)
VALUES
('STU-001', 'Aarav Sharma', '2004-04-12', 'Male', 'Indian', '9876543210', 'aarav@example.com', 'Delhi', 'Ravi Sharma, Meera Sharma', '9876500001', 'Central High School', 'Semester 3', 'Computer Science', 'Active');

INSERT INTO teachers
(teacher_id, name, department, specialization, email, phone, office_location, joining_date, salary, role, assigned_subjects)
VALUES
('TCH-001', 'Dr. Nisha Rao', 'Computer Science', 'Database Systems', 'nisha@example.com', '9876500020', 'Block A-204', '2022-07-01', 85000, 'Professor', 'Database Systems, Web Development');

INSERT INTO courses (course_id, course_name, credits, description, prerequisite) VALUES
('CSE-201', 'Database Management Systems', 4, 'Relational modeling, SQL, transactions, and indexing.', 'Programming Fundamentals'),
('CSE-202', 'Web Application Development', 3, 'Client-server web applications using modern JavaScript.', 'HTML and JavaScript');

INSERT INTO enrollments (student_id, course_id, status) VALUES (1, 1, 'Registered'), (1, 2, 'Registered');

INSERT INTO attendance (student_id, course_id, teacher_id, class_name, attendance_date, status) VALUES
(1, 1, 1, 'CSE-A', CURRENT_DATE, 'Present'),
(1, 2, 1, 'CSE-A', CURRENT_DATE, 'Late');

INSERT INTO marks (student_id, course_id, internal_marks, assignment, quiz, project, final_exam, total, grade, gpa) VALUES
(1, 1, 15, 10, 8, 18, 42, 93, 'A+', 4.00);

INSERT INTO fees (student_id, tuition_fee, hostel_fee, bus_fee, scholarship, paid_amount, pending_amount, payment_status, receipt_no) VALUES
(1, 50000, 20000, 5000, 10000, 40000, 25000, 'Partial', 'R-1001');

INSERT INTO schedules (class_name, room, day, start_time, end_time, teacher_id, teacher_name, course_id) VALUES
('CSE-A', 'Lab 2', 'Tuesday', '10:00:00', '11:00:00', 1, 'Dr. Nisha Rao', 1);

INSERT INTO notifications (title, message, type, target_role) VALUES
('Database Assignment', 'Submit ER diagram assignment by Friday.', 'New Assignment', 'Student'),
('Fee Reminder', 'Please clear pending fees before the due date.', 'Fee Reminder', 'Student');

-- Default password for all seed users is: admin123
INSERT INTO users (name, email, password_hash, role, student_id, teacher_id) VALUES
('Admin User', 'admin@example.com', 'admin123', 'Admin', NULL, NULL),
('Dr. Nisha Rao', 'nisha@example.com', 'admin123', 'Teacher', NULL, 1),
('Aarav Sharma', 'aarav@example.com', 'admin123', 'Student', 1, NULL);
